name = "aviator"
main = "src/index.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[d1_databases]]
binding = "DB"
database_name = "aviator-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
